1. Definir variable objetivo
        ↓
2. EDA
        ↓
3. Análisis de nulos
        ↓
4. Eliminar columnas >95%
        ↓
5. Revisar nulos estructurales
        ↓
6. Eliminar data leakage
        ↓
7. Ingeniería de características
        ↓
8. Encoding
        ↓
9. Escalamiento
        ↓
10. Train/Validation/Test
        ↓
11. Manejo de desbalance
        ↓
12. Construcción de la red
        ↓
13. Entrenamiento
        ↓
14. Evaluación
        ↓
15. Interpretabilidad
        ↓
16. Ajuste de hiperparámetros

# **Bibliotecas**

### **Funciones propias**

In [11]:
import sys
import os

sys.path.append(
    os.path.abspath("..")
)

In [12]:
from Funciones import get_column, resumen_variables

In [13]:
import pandas as pd
import numpy as np
import matplotlib as mpl

# **Análisis exploratorio**

In [14]:
# Configuración del display de pandas, para ver las tablas completas
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [22]:
df = pd.read_csv("../Data/raw/NFL_2015-2025.csv")

C:\Users\saiur\AppData\Local\Temp\ipykernel_24568\634073000.py:1: DtypeWarning: Columns (0: two_point_conv_result, 1: lateral_receiver_player_id, 2: lateral_receiver_player_name, 3: lateral_rusher_player_id, 4: lateral_rusher_player_name, 5: lateral_interception_player_id, 6: lateral_interception_player_name, 7: lateral_punt_returner_player_id, 8: lateral_punt_returner_player_name, 9: lateral_kickoff_returner_player_id, 10: lateral_kickoff_returner_player_name, 11: own_kickoff_recovery_player_id, 12: own_kickoff_recovery_player_name, 13: blocked_player_id, 14: blocked_player_name, 15: tackle_for_loss_2_player_id, 16: tackle_for_loss_2_player_name, 17: qb_hit_2_player_id, 18: qb_hit_2_player_name, 19: forced_fumble_player_2_team, 20: forced_fumble_player_2_player_id, 21: forced_fumble_player_2_player_name, 22: solo_tackle_2_team, 23: solo_tackle_2_player_id, 24: solo_tackle_2_player_name, 25: assist_tackle_3_player_id, 26: assist_tackle_3_player_name, 27: assist_tackle_3_team, 28: assist_tackle_4_player_id, 29: assist_tackle_4_player_name, 30: assist_tackle_4_team, 31: tackle_with_assist_2_player_id, 32: tackle_with_assist_2_player_name, 33: tackle_with_assist_2_team, 34: pass_defense_2_player_id, 35: pass_defense_2_player_name, 36: fumbled_2_player_id, 37: fumbled_2_player_name, 38: fumbled_2_team, 39: fumble_recovery_2_team, 40: fumble_recovery_2_player_id, 41: fumble_recovery_2_player_name, 42: safety_player_name, 43: safety_player_id, 44: end_clock_time, 45: surface) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../Data/raw/NFL_2015-2025.csv")

In [23]:
df.head(5)

,Unnamed: 0,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,side_of_field,yardline_100,game_date,quarter_seconds_remaining,half_seconds_remaining,game_seconds_remaining,game_half,quarter_end,drive,sp,qtr,down,goal_to_go,time,yrdln,ydstogo,ydsnet,desc,play_type,yards_gained,shotgun,no_huddle,qb_dropback,qb_kneel,qb_spike,qb_scramble,pass_length,pass_location,air_yards,yards_after_catch,run_location,run_gap,field_goal_result,kick_distance,extra_point_result,two_point_conv_result,home_timeouts_remaining,away_timeouts_remaining,timeout,timeout_team,td_team,td_player_name,td_player_id,posteam_timeouts_remaining,defteam_timeouts_remaining,total_home_score,total_away_score,posteam_score,defteam_score,score_differential,posteam_score_post,defteam_score_post,score_differential_post,no_score_prob,opp_fg_prob,opp_safety_prob,opp_td_prob,fg_prob,safety_prob,td_prob,extra_point_prob,two_point_conversion_prob,ep,epa,total_home_epa,total_away_epa,total_home_rush_epa,total_away_rush_epa,total_home_pass_epa,total_away_pass_epa,air_epa,yac_epa,comp_air_epa,comp_yac_epa,total_home_comp_air_epa,total_away_comp_air_epa,total_home_comp_yac_epa,total_away_comp_yac_epa,total_home_raw_air_epa,total_away_raw_air_epa,total_home_raw_yac_epa,total_away_raw_yac_epa,wp,def_wp,home_wp,away_wp,wpa,vegas_wpa,vegas_home_wpa,home_wp_post,away_wp_post,vegas_wp,vegas_home_wp,total_home_rush_wpa,total_away_rush_wpa,total_home_pass_wpa,total_away_pass_wpa,air_wpa,yac_wpa,comp_air_wpa,comp_yac_wpa,total_home_comp_air_wpa,total_away_comp_air_wpa,total_home_comp_yac_wpa,total_away_comp_yac_wpa,total_home_raw_air_wpa,total_away_raw_air_wpa,total_home_raw_yac_wpa,total_away_raw_yac_wpa,punt_blocked,first_down_rush,first_down_pass,first_down_penalty,third_down_converted,third_down_failed,fourth_down_converted,fourth_down_failed,incomplete_pass,touchback,interception,punt_inside_twenty,punt_in_endzone,punt_out_of_bounds,punt_downed,punt_fair_catch,kickoff_inside_twenty,kickoff_in_endzone,kickoff_out_of_bounds,kickoff_downed,kickoff_fair_catch,fumble_forced,fumble_not_forced,fumble_out_of_bounds,solo_tackle,safety,penalty,tackled_for_loss,fumble_lost,own_kickoff_recovery,own_kickoff_recovery_td,qb_hit,rush_attempt,pass_attempt,sack,touchdown,pass_touchdown,rush_touchdown,return_touchdown,extra_point_attempt,two_point_attempt,field_goal_attempt,kickoff_attempt,punt_attempt,fumble,complete_pass,assist_tackle,lateral_reception,lateral_rush,lateral_return,lateral_recovery,passer_player_id,passer_player_name,passing_yards,receiver_player_id,receiver_player_name,receiving_yards,rusher_player_id,rusher_player_name,rushing_yards,lateral_receiver_player_id,lateral_receiver_player_name,lateral_receiving_yards,lateral_rusher_player_id,lateral_rusher_player_name,lateral_rushing_yards,lateral_sack_player_id,lateral_sack_player_name,interception_player_id,interception_player_name,lateral_interception_player_id,lateral_interception_player_name,punt_returner_player_id,punt_returner_player_name,lateral_punt_returner_player_id,lateral_punt_returner_player_name,kickoff_returner_player_name,kickoff_returner_player_id,lateral_kickoff_returner_player_id,lateral_kickoff_returner_player_name,punter_player_id,punter_player_name,kicker_player_name,kicker_player_id,own_kickoff_recovery_player_id,own_kickoff_recovery_player_name,blocked_player_id,blocked_player_name,tackle_for_loss_1_player_id,tackle_for_loss_1_player_name,tackle_for_loss_2_player_id,tackle_for_loss_2_player_name,qb_hit_1_player_id,qb_hit_1_player_name,qb_hit_2_player_id,qb_hit_2_player_name,forced_fumble_player_1_team,forced_fumble_player_1_player_id,forced_fumble_player_1_player_name,forced_fumble_player_2_team,forced_fumble_player_2_player_id,forced_fumble_player_2_player_name,solo_tackle_1_team,solo_tackle_2_team,solo_tackle_1_player_id,solo_tackle_2_player_id,solo_tackle_1_player_name,solo_tackle_2_player_name,assist_tackle_1_player_id,assist_tackle_1_player_name,assist_tackle_1_team,assist_tackle_2_player_id,assist_tackle_2_player_name,assist_tackle_2_team,assist_tackle_3_player_id,assist_tackle_3_player_name,assist_tackle_3_team,assist_tackle_4_player_id,assist_tackle_4_player_name,assist_tackle_4_team,tackle_with_assist,tackle_with_assist_1_player_id,tackle_with_assist_1_player_name,tackle_with_assist_1_team,tackle_with_assist_2_player_id,tackle_with_assist_2_player_name,tackle_with_assist_2_team,pass_defense_1_player_id,pass_defense_1_player_name,pass_defense_2_player_id,pass_defense_2_player_name,fumbled_1_team,fumbled_1_player_id,fumbled_1_player_name,fumbled_2_player_id,fumbled_2_player_name,fumbled_2_team,fumble_recovery_1_team,fumble_recovery_1_yards,fumble_recovery_1_player_id,fumble_recovery_1_player_name,fumble_recovery_2_team,fumble_recovery_2_yards,fumble_recovery_2_player_id,fumble_recovery_2_player_name,sack_player_id,sack_player_name,half_sack_1_player_id,half_sack_1_player_name,half_sack_2_player_id,half_sack_2_player_name,return_team,return_yards,penalty_team,penalty_player_id,penalty_player_name,penalty_yards,replay_or_challenge,replay_or_challenge_result,penalty_type,defensive_two_point_attempt,defensive_two_point_conv,defensive_extra_point_attempt,defensive_extra_point_conv,safety_player_name,safety_player_id,season,cp,cpoe,series,series_success,series_result,order_sequence,start_time,time_of_day,stadium,weather,nfl_api_id,play_clock,play_deleted,play_type_nfl,special_teams_play,st_play_type,end_clock_time,end_yard_line,fixed_drive,fixed_drive_result,drive_real_start_time,drive_play_count,drive_time_of_possession,drive_first_downs,drive_inside20,drive_ended_with_score,drive_quarter_start,drive_quarter_end,drive_yards_penalized,drive_start_transition,drive_end_transition,drive_game_clock_start,drive_game_clock_end,drive_start_yard_line,drive_end_yard_line,drive_play_id_started,drive_play_id_ended,away_score,home_score,location,result,total,spread_line,total_line,div_game,roof,surface,temp,wind,home_coach,away_coach,stadium_id,game_stadium,aborted_play,success,passer,passer_jersey_number,rusher,rusher_jersey_number,receiver,receiver_jersey_number,pass,rush,first_down,special,play,passer_id,rusher_id,receiver_id,name,jersey_number,id,fantasy_player_name,fantasy_player_id,fantasy,fantasy_id,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe
0,0,1,2015_01_BAL_DEN,2015091309,DEN,BAL,REG,1,NaN,NaN,NaN,NaN,NaN,2015-09-13,900.0,1800.0,3600.0,Half1,0,NaN,0,1,NaN,0,15:00,DEN 35,0,NaN,GAME,NaN,NaN,0,0,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.239785,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.422024,0.577976,0.577976,0.422024,0.000000,0.000000,0.000000,NaN,NaN,0.310562,0.689438,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015,NaN,NaN,1,1,First down,1,"9/13/15, 16:25:26",NaN,Empower Field at Mile High,"Partly Sunny Temp: 88° F, Humidity: 8%, Wind: ...",10012015-0913-09a4-1137-8ec82c3543da,0,0,GAME_START,0,NaN,NaN,NaN,1,Punt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,19,Home,6,32,4.5,46.5,0,outdoors,grass,88.0,13.0,Gary Kubiak,John Harbaugh,DEN00,Sports Authority Field at Mile High,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,36,2015_01_BAL_DEN,2015091309,DEN,BAL,REG,1,BAL,away,DEN,DEN,35.0,2015-09-13,900.0,1800.0,3600.0,Half1,0,1.0,0,1,NaN,0,15:00,DEN 35,0,18.0,8-B.McManus kicks 65 yards from DEN 35 to end ...,kickoff,0.0,0,0,0.0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,NaN,NaN,3,3,0.0,NaN,NaN,NaN,NaN,3.0,3.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.004177,0.175739,0.005096,0.289366,0.215064,0.003269,0.307289,0.0,0.0,0.239785,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.422024,0.577976,0.577976,0.422024,0.000000,0.000000,0.000000,0.577976,0.422024,0.310562,0.689438,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B.McManus,00-0029822,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BAL,0.0,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,2015,NaN,NaN,1,1,First down,36,"9/13/15, 16:25:26",2015-09-13T20:25:26Z,Empower Field at Mile High,"Partly Sunny Temp: 88° F, Humidity: 8%, Wind: ...",10012015-0913-09a4-1137-8ec82c3543da,0,0,KICK_OFF,1,NaN,NaN,NaN,1,Punt,2015-09-13T20:25:26Z,6.0,3:27,1.0,0.0,0.0,1.0,1.0,0.0,KICKOFF,PUNT,15:00,11:33,BAL 20,BAL 38,36.0,187.0,13,19,Home,6,32,4.5,46.5,0,outdoors,grass,88.0,13.0,Gary Kubiak,John Harbaugh,DEN00,Sports Authority Field at Mile High,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,51,2015_01_BAL_DEN,2015091309,DEN,BAL,REG,1,BAL,away,DEN,BAL,80.0,2015-09-13,900.0,1800.0,3600.0,Half1,0,1.0,0,1,1.0,0,15:00,BAL 20,10,18.0,(15:00) 5-J.Flacco pass short left to 44-K.Jus...,pass,3.0,0,0,1.0,0,0,0,short,left,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,3,3,0.0,NaN,NaN,NaN,NaN,3.0,3.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.004177,0.175739,0.005096,0.289366,0.215064,0.003269,0.307289,0.0,0.0,0.239785,-0.337139,0.337139,-0.337139,0.000000,0.000000,0.337139,-0.337139,-0.337139,0.000000,-0.337139,0.000000,0.337139,-0.337139,0.000000,0.000000,0.337139,-0.337139,0.000000,0.000000,0.422024,0.577976,0.577976,0.422024,-0.001425,0.014361,-0.014361,0.579401,0.420599,0.310562,0.689438,0.000000,0.000000,0.001425,-0.001425,-0.001425,0.000000,-0.001425,0.000000,0.001425,-0.001425,0.000000,0.000000,0.001425,-0.001425,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,00-0026158,J.Flacco,3.0,00-0029892,K.Juszczyk,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DEN,NaN,00-0028224,NaN,C.Harris,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,2015,0.765811,23.418927,1,1,First down,51,"9/13/15, 16:25:26",2015-09-13T20:26:09Z,Empower Field at Mile High,"Partly Sunny Temp: 88° F, Humidity: 8%, Wind: ...",10012015-0913-09a4-1137-8ec82c3543da,0,0,PASS,0,NaN,NaN,NaN,1,Punt,2015-09-13T20:25:26Z,6.0,3:27,1.0,0.0,0.0,1.0,1.0,0.0,KICKOFF,PUNT,15:00,11:33,BAL 20,BAL 38,36.0,187.0,13,19,Home,6,32,4.5,46.5,0,outdoors,grass,88.0,13.0,Gary Kubiak,John Harbaugh,DEN00,Sports Authority Field at Mile High,0,0.0,J.Flacco,5.0,NaN,NaN,K.Juszczyk,44.0,1,0,0.0,0,1,00-0026158,NaN,00-0029892,J.Flacco,5.0,00-0026158,K.Juszczyk,00-0029892,K.Juszczyk,00-0029892,0,0,-0.337139,0.691718,4.699278,3.0,0.678964,0.225919,0.456481,54.351911
3,3,75,2015_01_BAL_DEN,2015091309,DEN,BAL,REG,1,BAL,away,DEN,BAL,77.0,2015-09-13,873.0,1773.0,3573.0,Half1,0,1.0,0,1,2.0,0,14:33,BAL 23,7,18.0,(14:33) 29-J.Forsett left guard to BAL 25 for ...,run,2.0,0,0,0.0,0,0,0,NaN,NaN,NaN,NaN,left,guard,NaN,NaN,NaN,NaN,3,3,0.0,NaN,NaN,NaN,NaN,3.0,3.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.004151,0.176419,0.005037,0.313898,0.211788,0.003409,0.285298,0.0,0.0,-0.097354,-0.262481,0.599620,-0.599620,0.262481,-0.262481,0.337139,-0.337139,NaN,NaN,0.000000,0.000000,0.337139,-0.337139,0.000000,0.000000,0.337139,-0.337139,0.000000,0.000000,0.420599,0.579401,0.579401,0.420599,-0.017304,-0.000147,0.000147,0.596705,0.403295,0.324924,0.675076,0.017304,-0.017304,0.001425,-0.001425,NaN,NaN,0.000000,0.000000,0.001425,-0.001425,0.000000,0.000000,0.001425,-0.001425,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,00-0026373,J.Forsett,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DEN,NaN,00-0029568,NaN,M.Jackson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,2015,NaN,NaN,1,1,First down,75,"9/13/15, 16:25:26",2015-09-13T20:26:36Z,Empower Field at Mile High,"Partly Sunny Temp: 88° F, Humidity: 8%, Wind: ...",10012015-0913-09a4-1137-8ec82c3543da,0,0,RUSH,0,NaN,NaN,NaN,1,Punt,2015-09-13T20:25:26Z,6.0,3:27,1.0,0.0,0.0,1.0,1.0,0.0,KICKOFF,PUNT,15:00,11:33,BAL 20,BAL 38,36.0,187.0,13,19,Home,6,32,4.5,46.5,0,outdoors,grass,88.0,13.0,Gary Kubiak,John Harbaugh,DEN00,Sports Authority Field at Mile High,0,0.0,NaN,NaN,J.Forsett,29.0,NaN,NaN,0,1,0.0,0,1,NaN,00-0026373,NaN,J.Forsett,29.0,00-0026373,J.Forsett,00-0026373,J.Forsett,00-0026373,0,0,-0.262481,NaN,NaN,NaN,NaN,NaN,0.545905,-54.590458
4,4,96,2015_01_BAL_DEN,2015091309,DEN,BAL,REG,1,BAL,away,DEN,BAL,75.0,2015-09-13,832.0,1732.0,3532.0,Half1,0,1.0,0,1,3.0,0,13:52,BAL 25,5,18.0,(13:52) (Shotgun) 5-J.Flacco pass short middle...,pass,10.0,1,0,1.0,0,0,0,short,middle,4.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,3,3,0.0,NaN,NaN,NaN,NaN,3.0,3.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.004316,0.191080,0.004958,0.323530,0.206798,0.003518,0.265800,0.0,0.0,-0.359835,1.661242,-1.061622,1.061622,0.262481,-0.262481,-1.324103,1.324103,-0.791399,2.452641,-0.791399,2.452641,1.128537,-1.128537,-2.452641,2.452641,1.128537,-1.128537,-2.452641,2.452641,0.403295,0.596705,0.596705,0.403295,0.045358,0.054237,-0.054237,0.551347,0.448653,0.324777,0.675223,0.017304,-0.017304,-0.043933,0.043933,0.000000,0.045358,0.000000,0.045358,0.001425,-0.001425,-0.045358,0.045358,0.001425,-0.001425,-0.045358,0.045358,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,00-0026158,J.Flacco,10.0,00-0020337,S.Smith,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00-0023445,D.Ware,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DEN,NaN,00-0029620,NaN,B.Marshall,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,2015,0.510176,48.982388,1,1,First down,96,"9/13/15, 16:25:26",2015-09-13T20:27:17Z,Empower Field at Mile High,"Partly Sunny Temp: 88° F, Humidity: 8%, Wind: ...",10012015-0913-09a4-1137-8ec82c3543da,0,0,PASS,0,NaN,NaN,NaN,1,Punt,2015-09-13T20:25:26Z,6.0,3:27,1.0,0.0,0.0,1.0,1.0,0.0,KICKOFF,PUNT,15:00,11:33,BAL 20,BAL 38,36.0,187.0,13,19,Home,6,32,4.5,46.5,0,outdoors,grass,88.0,13.0,Gary Kubiak,John Harbaugh,DEN00,Sports Authority Field at Mile High,0,1.0,J.Flacco,5.0,NaN,NaN,S.Smith,89.0,1,0,1.0,0,1,00-0026158,NaN,00-0020337,J.Flacco,5.0,00-0026158,S.Smith,00-0020337,S.Smith,00-0020337,0,0,1.661242,1.794671,4.662650,2.0,0.712350,0.712350,0.968533,3.146732

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 532376 entries, 0 to 532375
Columns: 373 entries, Unnamed: 0 to pass_oe
dtypes: float64(174), int64(40), str(159)
memory usage: 1.8 GB

In [21]:
df.describe()

,Unnamed: 0,play_id,old_game_id,week,yardline_100,quarter_seconds_remaining,half_seconds_remaining,game_seconds_remaining,quarter_end,drive,sp,qtr,down,goal_to_go,ydstogo,ydsnet,yards_gained,shotgun,no_huddle,qb_dropback,qb_kneel,qb_spike,qb_scramble,air_yards,yards_after_catch,kick_distance,home_timeouts_remaining,away_timeouts_remaining,timeout,posteam_timeouts_remaining,defteam_timeouts_remaining,total_home_score,total_away_score,posteam_score,defteam_score,score_differential,posteam_score_post,defteam_score_post,score_differential_post,no_score_prob,opp_fg_prob,opp_safety_prob,opp_td_prob,fg_prob,safety_prob,td_prob,extra_point_prob,two_point_conversion_prob,ep,epa,total_home_epa,total_away_epa,total_home_rush_epa,total_away_rush_epa,total_home_pass_epa,total_away_pass_epa,air_epa,yac_epa,comp_air_epa,comp_yac_epa,total_home_comp_air_epa,total_away_comp_air_epa,total_home_comp_yac_epa,total_away_comp_yac_epa,total_home_raw_air_epa,total_away_raw_air_epa,total_home_raw_yac_epa,total_away_raw_yac_epa,wp,def_wp,home_wp,away_wp,wpa,vegas_wpa,vegas_home_wpa,home_wp_post,away_wp_post,vegas_wp,vegas_home_wp,total_home_rush_wpa,total_away_rush_wpa,total_home_pass_wpa,total_away_pass_wpa,air_wpa,yac_wpa,comp_air_wpa,comp_yac_wpa,total_home_comp_air_wpa,total_away_comp_air_wpa,total_home_comp_yac_wpa,total_away_comp_yac_wpa,total_home_raw_air_wpa,total_away_raw_air_wpa,total_home_raw_yac_wpa,total_away_raw_yac_wpa,punt_blocked,first_down_rush,first_down_pass,first_down_penalty,third_down_converted,third_down_failed,fourth_down_converted,fourth_down_failed,incomplete_pass,touchback,interception,punt_inside_twenty,punt_in_endzone,punt_out_of_bounds,punt_downed,punt_fair_catch,kickoff_inside_twenty,kickoff_in_endzone,kickoff_out_of_bounds,kickoff_downed,kickoff_fair_catch,fumble_forced,fumble_not_forced,fumble_out_of_bounds,solo_tackle,safety,penalty,tackled_for_loss,fumble_lost,own_kickoff_recovery,own_kickoff_recovery_td,qb_hit,rush_attempt,pass_attempt,sack,touchdown,pass_touchdown,rush_touchdown,return_touchdown,extra_point_attempt,two_point_attempt,field_goal_attempt,kickoff_attempt,punt_attempt,fumble,complete_pass,assist_tackle,lateral_reception,lateral_rush,lateral_return,lateral_recovery,passing_yards,receiving_yards,rushing_yards,lateral_receiving_yards,lateral_rushing_yards,lateral_sack_player_id,lateral_sack_player_name,tackle_with_assist,fumble_recovery_1_yards,fumble_recovery_2_yards,return_yards,penalty_yards,replay_or_challenge,defensive_two_point_attempt,defensive_two_point_conv,defensive_extra_point_attempt,defensive_extra_point_conv,season,cp,cpoe,series,series_success,order_sequence,play_clock,play_deleted,special_teams_play,st_play_type,end_yard_line,fixed_drive,drive_play_count,drive_first_downs,drive_inside20,drive_ended_with_score,drive_quarter_start,drive_quarter_end,drive_yards_penalized,drive_play_id_started,drive_play_id_ended,away_score,home_score,result,total,spread_line,total_line,div_game,temp,wind,aborted_play,success,passer_jersey_number,rusher_jersey_number,receiver_jersey_number,pass,rush,first_down,special,play,jersey_number,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe
count,532376.000000,532376.000000,5.323760e+05,532376.000000,495041.000000,532108.000000,532108.000000,532108.000000,532376.000000,526315.000000,532376.000000,532376.000000,447831.000000,532376.00000,532376.000000,526315.000000,516197.000000,532376.000000,532376.000000,516734.000000,532376.000000,532376.000000,532376.000000,207386.000000,132767.000000,81868.000000,532376.000000,532376.000000,516197.000000,504016.000000,504016.000000,532376.000000,532376.000000,503986.000000,503986.000000,503986.000000,504016.000000,504016.000000,504016.000000,532376.000000,532376.000000,532376.000000,532376.000000,532376.000000,532376.000000,532376.000000,532376.000000,532376.000000,526282.000000,526280.000000,532376.000000,532376.000000,532376.000000,532376.000000,532376.000000,532376.000000,206633.000000,206632.000000,516191.000000,516190.000000,532376.000000,532376.000000,532376.000000,532376.000000,532376.000000,532376.000000,532376.000000,532376.000000,529310.000000,529310.000000,532376.000000,532376.000000,524488.000000,524488.000000,529348.000000,495589.000000,495589.000000,5.293100e+05,532376.000000,532376.000000,532376.000000,532376.000000,532376.000000,206633.000000,206633.000000,516191.000000,516191.000000,532376.000000,532376.000000,532376.000000,532376.000000,532376.000000,532376.000000,532376.000000,532376.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,532376.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516207.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,516197.000000,132777.000000,132777.000000,161146.000000,138.000000,27.000000,0.0,0.0,516197.000000,6548.000000,66.000000,516197.000000,37766.000000,532376.000000,516197.000000,516197.000000,516197.0,516197.0,532376.000000,200437.000000,200437.000000,532376.000000,532376.000000,532376.000000,532376.0,532376.000000,532376.000000,0.0,0.0,532376.000000,526315.000000,526315.000000,526315.000000,526315.000000,526315.000000,526315.000000,526315.000000,526315.000000,526310.000000,532376.000000,532376.000000,532376.000000,532376.00000,532376.000000,532376.000000,532376.000000,350483.000000,350483.000000,532376.000000,526280.000000,245360.000000,161129.000000,213876.000000,532376.000000,532376.000000,516197.000000,532376.000000,532376.000000,395674.000000,532376.000000,532376.000000,526280.000000,186924.000000,186925.000000,186925.00000,186925.000000,186925.000000,405378.000000,394450.000000
mean,24209.432816,2141.182843,2.020241e+09,9.671914,48.806790,411.272417,808.526545,1707.315513,0.017396,11.653196,0.074511,2.566806,1.994125,0.05026,7.184509,41.181935,4.031120,0.502419,0.077740,0.449123,0.008909,0.001527,0.020104,8.002064,5.186063,48.907339,2.540950,2.525550,0.044878,2.572972,2.584716,12.017916,10.884307,10.600421,11.889181,-1.288760,10.863447,11.899164,-1.035717,0.123949,0.085321,0.001934,0.133777,0.239156,0.002441,0.312623,0.024796,0.001249,1.883203,-0.007335,0.161605,-0.161605,-0.103732,0.103732,-0.099328,0.099328,0.460060,-0.312485,0.043554,0.169216,-0.224541,0.224541,-0.024188,0.024188,-0.564873,0.564873,0.349437,-0.349437,0.508348,0.491652,0.556623,0.443377,0.000665,0.001010,-0.000021,0.556914,0.443046,5.083253e-01,0.549229,-0.008831,0.008831,-0.013099,0.013099,0.003259,0.000857,0.001397,0.004097,-0.008261,0.008261,-0.002157,0.002157,-0.009806,0.009806,-0.005745,0.005745,0.000240,0.075022,0.138470,0.021639,0.060000,0.091626,0.007735,0.006978,0.135429,0.037342,0.009225,0.018175,0.000025,0.004884,0.006255,0.013237,0.004587,0.008861,0.000498,0.000025,0.000217,0.009392,0.004630,0.001288,0.450088,0.000333,0.073162,0.027815,0.006226,0.000139,0.000004,0.063373,0.312919,0.431729,0.027873,0.030153,0.017966,0.010358,0.001674,0.027263,0.002720,0.022790,0.060125,0.048567,0.013952,0.257222,0.151115,0.000267,0.000052,0.000099,0.001734,11.158604,11.152956,4.302235,5.775362,6.222222,NaN,NaN,0.048369,2.273213,2.560606,0.863200,8.416194,0.007681,0.000143,0.000031,0.0,0.0,2020.047299,0.659705,0.268772,29.318215,0.577620,2140.487916,0.0,0.000002,0.131905,NaN,NaN,11.594403,7.504795,2.556097,0.408267,0.491850,2.518260,2.640043,0.196116,2042.536333,2256.691277,22.139849,23.952571,1.812723,46.09242,1.844833,45.310802,0.354308,57.765615,8.242754,0.002211,0.416867,8.742374,24.011084,37.751973,0.460883,0.282825,0.232752,0.153779,0.764871,14.964536,0.085509,0.515953,-0.000475,0.713856,5.414541,3.57545,0.785032,0.586606,0.627550,-0.711821
std,13990.383850,1253.644693,3.188438e+06,5.448589,24.317738,282.313867,560.074631,1059.219835,0.130740,6.765407,0.262601,1.131872,1.002891,0.21848,4.902374,28.878230,7.830439,0.499995,0.267763,0.497405,0.093967,0.039049,0.140357,10.119599,6.842559,14.360702,0.785072,0.796657,0.207037,0.759743,0.736154,10.098820,9.642267,9.599282,10.040791,10.563998,9.674993,10.045136,10.649214,0.199157,0.065808,0.004469,0.108491,0.160381,0.002017,0.181693,0.150152,0.024284,1.699517,1.258746,12.446140,12.446140,5.287824,5.287824,10.521941,10.521941,1.384221,1.925442,0.627110,0.588293,6.160112,6.160112,6.534029,6.534029,9.455421,9.455421,12.301110,12.301110,0.296477,0.296477,0.292730,0.292730,0.040150,0.038469,0.038438,0.291343,0.291335,3.199645e-01,0.317598,0.152365,0.152365,0.259598,0.259598,0.045235,0.058676,0.022955,0.028268,0.165753,0.165753,0.245181,0.245181,0.210926,0.210926,0.317170,0.317170,0.015497,0.263427,0.345393,0.145502,0.237488,0.288497,0.087610,0.083242,0.342181,0.189599,0.095604,0.133585,0.005018,0.069713,0.078843,0.114289,0.067575,0.093715,0.022308,0.005018,0.014728,0.096455,0.067887,0.035869,0.497503,0.018251,0.260402,0.164443,0.078661,0.011809,0.001968,0.243633,0.463682,0.495318,0.164609,0.171009,0.132828,0.101248,0.040878,0.162849,0.052082,0.149233,0.237719,0.214961,0.117292,0.437103,0.358161,0.016348,0.007232,0.009939,0.041603,10.024748,10.018495,6.278427,10.513126,8.477723,NaN,NaN,0.214545,9.077608,7.614013,4.871788,5.377349,0.087302,0.011972,0.005567,0.0,0.0,3.164420,0.172669,43.978215,17.079918,0.493939,1253.364726,0.0,0.001371,0.338388,NaN,NaN,6.788247,3.665571,1.918592,0.491513,0.499934,1.130682,1.122601,7.873783,1243.183528,1245.087827,9.751185,10.022180,13.968411,13.99796,5.963841,4.350783,0.478303,17.525881,5.120487,0.046968,0.493041,5.104977,12.122930,32.440274,0.498468,0.450372,0.422586,0.360737,0.424080,11.449730,0.279638,0.499746,1.247465,0.518773,2.488136,2.51001,0.250818,0.356648,0.240424,41.963155
min,0.000000,1.000000,2.015091e+09,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.00000,0.000000,-36.000000,-38.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-90.000000,-14.000000,-1.000000,0.000000,-1.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,-56.000000,0.000000,0.000000,-56.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-3.661654,-13.584859,-63.419816,-62.796222,-33.031181,-27.207561,-56.446764,-49.760438,-9.400001,-14.000000,-9.400001,-10.914923,-34.257044,-30.630452,-33.753985,-35.912690,-67.523506,-62.424389,-66.813266,-83.977837,0.000029,0.000023,0.000000,0.000000,-0.999202,-0.999886,-0.999886,0.000000,0.000000,7.071142e-08,0.000000,-1.180774,-0.973487,-1.707958,-1.317772,-0.998078,-0.974364,-0.979609,-0.974364,-1.944425,-3.017507,-2.572757,-2.106909,-3.031269,-3.905426,-3.709718,-3.568553,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-24.000000,-16.000000,-34.000000,-23.000000,-20.000000,NaN,NaN,0.000000,-15.000000,-16.000000,-19.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,2015.000000,0.138876,-92.344004,1.000000,0.000000,1.000000,0.0,0.000000,0.000000,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,-50.000000,35.000000,36.000000,0.000000,0.000000,-49.000000,3.00000,-18.000000,28.500000,0.000000,-6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-13.584859,-3.181688,0.279263,0.00000,0.000000,0.000000,0.010774,-99.538189
25%,12099.000000,1061.000000,2.017122e+09,5.000000,31.000000,147.000000,279.000000,785.000000,0.000000,6.000000,0.000000,2.000000,1.000000,0.00000,3.000000,15.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,33.000000,2.000000,2.000000,0.000000,2.000000,2.000000,3.000000,3.000000,3.000000,3.000000,-7.000000,3.000000,3.000000,-7.000000,0.005142,0.022466,0.000427,0.029161,0.160296,0.000844,0.209654,0.000000,0.000000,0.764220,-0.558430,-6.849463,-7.158779,-2.953912,-2.728135,-5.965351,-5.786225,-0.546961,-0.736214,0.000000,0.000000,-3.587777,-3.248768,-3.683753,-3.661945,-5.645113,-4.607008,-6.225257,-6.765470,0.270617,0.252651,0.340556,0.204468,-0.013782,-0.011457,-0.010415,0.341809,0.206114,2.252624e-01,0.277196,-0.089233,-0.076677,-0.179956,-0.168404,0.000000,-0.015706,0.000000,0.000000,-0.053878,-0.044494,-0.119570,-0.118108,-0.057471,-0.046342,-0.154181,-0.142335,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,5.000000,1.000000,0.000000,3.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.0,0.0,2017.000000,0.551371,-41.152617,15.000000,0.000000,1060.000000,0.0,0.000000,0.000000,NaN,NaN,6.000000,4.000000,1.000000,0.000000,0.000000,2.000000,2.000000,0.000000,968.000000,1185.000000,16.000000,17.000000,-6.000000,36.00000,-3.000000,42.500000,0.000000,45.000000,5.000000,0.000000,0.000000,4.000000,20.000000,13.000000,0.000000,0.000000,0.000000,0.000000,1.000000,7.000000,0.000000,0.000000,-0.556237,0.319163,3.714436,2.00000,0.566231,0.243605,0.454733,-41.875686
50%,24198.000000,2126.000000,2.020113e+09,10.000000,50.000000,392.000000,794.000000,1800.000000,0.000000,11.000000,0.000000,3.000000,2.000000,0.00000,9.000000,42.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,3.000000,49.000000,3.000000,3.000000,0.000000,3.000000,3.000000,10.000000,10.000000,9.000000,10.000000,0.000000,9.000000,10.000000,0.000000,0.026802,0.083322,0.001161,0.123448,0.217078,0.002278,0.339636,0.000000,0.000000,1.592994,0.000000,0.002622,-0.002622,0.000000,0.000000,0.000000,0.000000,0.209131,0.002238,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.211545,0.211545,0.003598,-0.003598,0.518700,0.481300,0.575019,0.424981,0.000000,0.000000,0.000000,0.578527,0.421433,5.151328e-01,0.577928,-0.000093,0.000093,0.000172,-0.000172,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,9.000000,3.000000,4.000000,4.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.0,0.0,2020.000000,0.710293,19.041663,29.000000,1.000000,2125.000000,0.0,0.000000,0.000000,NaN,NaN,11.000000,7.000000,2.000000,0.000000,0.000000,3.000000,3.000000,0.000000,2042.000000,2231.000000,22.000000,24.000000,3.000000,45.00000,3.000000,45.000000,0.000000,58.000000,7.000000,0.000000,0.000000,8.000000,26.000000,19.000000,0.000000,0.000000,0.000000,0.000000,1.000000,12.000000,0.000000,1.000000,0.000000,0.591637,4.582018,3.00000,0.985373,0.492869,0.597089,4.035330
75%,36298.000000,3191.000000,2.023102e+09,14.000000,70.000000,656.000000,1290.000000,2599.000000,0.000000,17.000000,0.000000,4.000000,3.000000,0.00000,10.000000,68.000000,6.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,12.000000,7.000000,65.000000,3.000000,3.000000,0.000000,3.000000,3.000000,19.000000,17.000000,17.000000,17.000000,4.000000,17.000000,17.000000,5.000000,0.155316,0.135425,0.002197,0.223034,0.303454,0.003568,0.421255,0.000000,0.000000,3.003487,0.525643,7.158779,6.849463,2.728135,2.953912,5.786225,5.965351,1.346904,0.592387,0.000000,0.000000,3.248768,3.587777,3.661945,3.683753,4.607008,5.645113,6.765470,6.225257,0.747349,0.729383,0.795532,0.659444,0.010561,0.009199,0.010433,0.793853,0.658133,7.928288e-01,0.835755,0.076677,0.089233,0.168404,0.179956,0.000000,0.012510,0.000000,0.000000,0.044494,0.053878,0.118108,0.119570,0.046342,0.057471,0.142335,0.154181,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,14.000000,6.000000,10.000000,9.500000,NaN,NaN,0.000000,0.000000,1.000000,0.000000,10.000000,0.000000,0.000000,0.000000,0.0,0.0,2023.000000,0.791139,29.733044,44.000000,1.000000,3191.000000,0.0,0.000000,0.000000,NaN,NaN,17.000000,10.000000,4.000000,1.000000,1.000000,4.000000,4.000000,0.000000,3082.000000,3308.000000,29.000000,30.000000,10.000000,55.00000,6.000000,48.000000,1.000000,71.000000,11.000000,0.000000,1.000000,12.000000,30.000000,82.000000,1.000000,1.000000,0.000000,0.000000,1.000000,23.000000,0.000000,1.000000,0.528364,0.963076,6.723092,5.00000,1.000000,0.999232,0.857065,33.596668
max,49921.000000,5921.000000,2.026021e+09,22.000000,99.000000,900.000000,1800.000000,3600.000000,1.000000,38.000000,1.000000,5.000000,4.000000,1.00000,46.000000,99.000000,99.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,65.000000,88.000000,84.000000,3.000000,3.000000,1.000000,3.000000,3.000000,70.000000,59.000000,70.000000,70.000000,55.000000,70.000000,70.000000,56.000000,1.000000,0.428207,0.195527,0.518709,0.997679,0.062991,0.933588,0.989279,0.473500,6.597472,8.882384,62.796222,63.419816,27.207561,33.031181,49.760438,56.446764,7.454971,9.848225,6.871572,9.848225,30.630452,34.257044,35.912690,33.753985,62.424389,67.523506,83.977837,66.813266,0.999977,0.999971,1.000000,1.000000,0.998998,0.999857,0.999857,1.000000,1.000000,9.999986e-01,1.000000,0.973487,1.180774,1.317772,1.707958,0.975666,1.000000,0.975666,1.000000,3.017507,1.944425,2.106909,2.572757,3.905426,3.031269,3.568553,3.709718,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,98.000000,98.000000,99.000000,52.000000,32.000000,NaN,NaN,1.000000,102.000000,28.000000,108.000000,66.000000,1.000000,1.000000,1.000000,0.0,0.0,2025.000000,0.926071,85.264441,83.000000,1.000000,5921.000000,0.0,1.000000,1.000000,NaN,NaN,38.000000,21.000000,9.000000,1.000000,1.000000,5.000000,5.000000,77.000000,5748.000000,5899.000000,59.000000,70.000000,50.000000,105.00000,22.000000,63.500000,1.000000,97.000000,71.000000,1.000000,1.000000,92.000000,99.000000,99.000000,1.000000,1.000000,1.000000,1.000000,1.000000,99.000000,1.000000,1.000000,8.882384,9.585749,30.100439,48.00000,1.000000,1.000000,0.998187,97.995057

In [22]:
columnas = list(df.columns)
columnas

['Unnamed: 0',
 'play_id',
 'game_id',
 'old_game_id',
 'home_team',
 'away_team',
 'season_type',
 'week',
 'posteam',
 'posteam_type',
 'defteam',
 'side_of_field',
 'yardline_100',
 'game_date',
 'quarter_seconds_remaining',
 'half_seconds_remaining',
 'game_seconds_remaining',
 'game_half',
 'quarter_end',
 'drive',
 'sp',
 'qtr',
 'down',
 'goal_to_go',
 'time',
 'yrdln',
 'ydstogo',
 'ydsnet',
 'desc',
 'play_type',
 'yards_gained',
 'shotgun',
 'no_huddle',
 'qb_dropback',
 'qb_kneel',
 'qb_spike',
 'qb_scramble',
 'pass_length',
 'pass_location',
 'air_yards',
 'yards_after_catch',
 'run_location',
 'run_gap',
 'field_goal_result',
 'kick_distance',
 'extra_point_result',
 'two_point_conv_result',
 'home_timeouts_remaining',
 'away_timeouts_remaining',
 'timeout',
 'timeout_team',
 'td_team',
 'td_player_name',
 'td_player_id',
 'posteam_timeouts_remaining',
 'defteam_timeouts_remaining',
 'total_home_score',
 'total_away_score',
 'posteam_score',
 'defteam_score',
 'score_differential',
 'posteam_score_post',
 'defteam_score_post',
 'score_differential_post',
 'no_score_prob',
 'opp_fg_prob',
 'opp_safety_prob',
 'opp_td_prob',
 'fg_prob',
 'safety_prob',
 'td_prob',
 'extra_point_prob',
 'two_point_conversion_prob',
 'ep',
 'epa',
 'total_home_epa',
 'total_away_epa',
 'total_home_rush_epa',
 'total_away_rush_epa',
 'total_home_pass_epa',
 'total_away_pass_epa',
 'air_epa',
 'yac_epa',
 'comp_air_epa',
 'comp_yac_epa',
 'total_home_comp_air_epa',
 'total_away_comp_air_epa',
 'total_home_comp_yac_epa',
 'total_away_comp_yac_epa',
 'total_home_raw_air_epa',
 'total_away_raw_air_epa',
 'total_home_raw_yac_epa',
 'total_away_raw_yac_epa',
 'wp',
 'def_wp',
 'home_wp',
 'away_wp',
 'wpa',
 'vegas_wpa',
 'vegas_home_wpa',
 'home_wp_post',
 'away_wp_post',
 'vegas_wp',
 'vegas_home_wp',
 'total_home_rush_wpa',
 'total_away_rush_wpa',
 'total_home_pass_wpa',
 'total_away_pass_wpa',
 'air_wpa',
 'yac_wpa',
 'comp_air_wpa',
 'comp_yac_wpa',
 'total_home_comp_air_wpa',
 'total_away_comp_air_wpa',
 'total_home_comp_yac_wpa',
 'total_away_comp_yac_wpa',
 'total_home_raw_air_wpa',
 'total_away_raw_air_wpa',
 'total_home_raw_yac_wpa',
 'total_away_raw_yac_wpa',
 'punt_blocked',
 'first_down_rush',
 'first_down_pass',
 'first_down_penalty',
 'third_down_converted',
 'third_down_failed',
 'fourth_down_converted',
 'fourth_down_failed',
 'incomplete_pass',
 'touchback',
 'interception',
 'punt_inside_twenty',
 'punt_in_endzone',
 'punt_out_of_bounds',
 'punt_downed',
 'punt_fair_catch',
 'kickoff_inside_twenty',
 'kickoff_in_endzone',
 'kickoff_out_of_bounds',
 'kickoff_downed',
 'kickoff_fair_catch',
 'fumble_forced',
 'fumble_not_forced',
 'fumble_out_of_bounds',
 'solo_tackle',
 'safety',
 'penalty',
 'tackled_for_loss',
 'fumble_lost',
 'own_kickoff_recovery',
 'own_kickoff_recovery_td',
 'qb_hit',
 'rush_attempt',
 'pass_attempt',
 'sack',
 'touchdown',
 'pass_touchdown',
 'rush_touchdown',
 'return_touchdown',
 'extra_point_attempt',
 'two_point_attempt',
 'field_goal_attempt',
 'kickoff_attempt',
 'punt_attempt',
 'fumble',
 'complete_pass',
 'assist_tackle',
 'lateral_reception',
 'lateral_rush',
 'lateral_return',
 'lateral_recovery',
 'passer_player_id',
 'passer_player_name',
 'passing_yards',
 'receiver_player_id',
 'receiver_player_name',
 'receiving_yards',
 'rusher_player_id',
 'rusher_player_name',
 'rushing_yards',
 'lateral_receiver_player_id',
 'lateral_receiver_player_name',
 'lateral_receiving_yards',
 'lateral_rusher_player_id',
 'lateral_rusher_player_name',
 'lateral_rushing_yards',
 'lateral_sack_player_id',
 'lateral_sack_player_name',
 'interception_player_id',
 'interception_player_name',
 'lateral_interception_player_id',
 'lateral_interception_player_name',
 'punt_returner_player_id',
 'punt_returner_player_name',
 'lateral_punt_returner_player_id',
 'lateral_punt_returner_player_name',
 'kickoff_returner_player_name',
 'kickoff_returner_player_id',
 'lateral_kickoff_returner_player_id',
 'lateral_kickoff_returner_player_name',
 'punter_player_id',
 'punter_player_name',
 'kicker_player_name',
 'kicker_player_id',
 'own_kickoff_recovery_player_id',
 'own_kickoff_recovery_player_name',
 'blocked_player_id',
 'blocked_player_name',
 'tackle_for_loss_1_player_id',
 'tackle_for_loss_1_player_name',
 'tackle_for_loss_2_player_id',
 'tackle_for_loss_2_player_name',
 'qb_hit_1_player_id',
 'qb_hit_1_player_name',
 'qb_hit_2_player_id',
 'qb_hit_2_player_name',
 'forced_fumble_player_1_team',
 'forced_fumble_player_1_player_id',
 'forced_fumble_player_1_player_name',
 'forced_fumble_player_2_team',
 'forced_fumble_player_2_player_id',
 'forced_fumble_player_2_player_name',
 'solo_tackle_1_team',
 'solo_tackle_2_team',
 'solo_tackle_1_player_id',
 'solo_tackle_2_player_id',
 'solo_tackle_1_player_name',
 'solo_tackle_2_player_name',
 'assist_tackle_1_player_id',
 'assist_tackle_1_player_name',
 'assist_tackle_1_team',
 'assist_tackle_2_player_id',
 'assist_tackle_2_player_name',
 'assist_tackle_2_team',
 'assist_tackle_3_player_id',
 'assist_tackle_3_player_name',
 'assist_tackle_3_team',
 'assist_tackle_4_player_id',
 'assist_tackle_4_player_name',
 'assist_tackle_4_team',
 'tackle_with_assist',
 'tackle_with_assist_1_player_id',
 'tackle_with_assist_1_player_name',
 'tackle_with_assist_1_team',
 'tackle_with_assist_2_player_id',
 'tackle_with_assist_2_player_name',
 'tackle_with_assist_2_team',
 'pass_defense_1_player_id',
 'pass_defense_1_player_name',
 'pass_defense_2_player_id',
 'pass_defense_2_player_name',
 'fumbled_1_team',
 'fumbled_1_player_id',
 'fumbled_1_player_name',
 'fumbled_2_player_id',
 'fumbled_2_player_name',
 'fumbled_2_team',
 'fumble_recovery_1_team',
 'fumble_recovery_1_yards',
 'fumble_recovery_1_player_id',
 'fumble_recovery_1_player_name',
 'fumble_recovery_2_team',
 'fumble_recovery_2_yards',
 'fumble_recovery_2_player_id',
 'fumble_recovery_2_player_name',
 'sack_player_id',
 'sack_player_name',
 'half_sack_1_player_id',
 'half_sack_1_player_name',
 'half_sack_2_player_id',
 'half_sack_2_player_name',
 'return_team',
 'return_yards',
 'penalty_team',
 'penalty_player_id',
 'penalty_player_name',
 'penalty_yards',
 'replay_or_challenge',
 'replay_or_challenge_result',
 'penalty_type',
 'defensive_two_point_attempt',
 'defensive_two_point_conv',
 'defensive_extra_point_attempt',
 'defensive_extra_point_conv',
 'safety_player_name',
 'safety_player_id',
 'season',
 'cp',
 'cpoe',
 'series',
 'series_success',
 'series_result',
 'order_sequence',
 'start_time',
 'time_of_day',
 'stadium',
 'weather',
 'nfl_api_id',
 'play_clock',
 'play_deleted',
 'play_type_nfl',
 'special_teams_play',
 'st_play_type',
 'end_clock_time',
 'end_yard_line',
 'fixed_drive',
 'fixed_drive_result',
 'drive_real_start_time',
 'drive_play_count',
 'drive_time_of_possession',
 'drive_first_downs',
 'drive_inside20',
 'drive_ended_with_score',
 'drive_quarter_start',
 'drive_quarter_end',
 'drive_yards_penalized',
 'drive_start_transition',
 'drive_end_transition',
 'drive_game_clock_start',
 'drive_game_clock_end',
 'drive_start_yard_line',
 'drive_end_yard_line',
 'drive_play_id_started',
 'drive_play_id_ended',
 'away_score',
 'home_score',
 'location',
 'result',
 'total',
 'spread_line',
 'total_line',
 'div_game',
 'roof',
 'surface',
 'temp',
 'wind',
 'home_coach',
 'away_coach',
 'stadium_id',
 'game_stadium',
 'aborted_play',
 'success',
 'passer',
 'passer_jersey_number',
 'rusher',
 'rusher_jersey_number',
 'receiver',
 'receiver_jersey_number',
 'pass',
 'rush',
 'first_down',
 'special',
 'play',
 'passer_id',
 'rusher_id',
 'receiver_id',
 'name',
 'jersey_number',
 'id',
 'fantasy_player_name',
 'fantasy_player_id',
 'fantasy',
 'fantasy_id',
 'out_of_bounds',
 'home_opening_kickoff',
 'qb_epa',
 'xyac_epa',
 'xyac_mean_yardage',
 'xyac_median_yardage',
 'xyac_success',
 'xyac_fd',
 'xpass',
 'pass_oe']

In [23]:
nulos = (
    pd.DataFrame({
        'nulos': df.isnull().sum(),
        'porcentaje': (df.isnull().sum() / len(df)) * 100
    })
    .query('nulos > 0')
    .sort_values(by='porcentaje', ascending=False)
    .reset_index()
)

nulos = nulos.rename(columns={'index': 'columna'})
nulos.index = range(1, len(nulos) + 1)

nulos

                                  columna   nulos  porcentaje
1                           end_yard_line  532376  100.000000
2                            st_play_type  532376  100.000000
3                lateral_sack_player_name  532376  100.000000
4                  lateral_sack_player_id  532376  100.000000
5          tackle_with_assist_2_player_id  532375   99.999812
6        tackle_with_assist_2_player_name  532375   99.999812
7               tackle_with_assist_2_team  532375   99.999812
8           tackle_for_loss_2_player_name  532374   99.999624
9             tackle_for_loss_2_player_id  532374   99.999624
10            assist_tackle_3_player_name  532369   99.998685
11            assist_tackle_4_player_name  532369   99.998685
12                   assist_tackle_4_team  532369   99.998685
13                   assist_tackle_3_team  532369   99.998685
14              assist_tackle_3_player_id  532369   99.998685
15              assist_tackle_4_player_id  532369   99.998685
16        lateral_punt_returner_player_id  532365   99.997934
17      lateral_punt_returner_player_name  532365   99.997934
18       lateral_interception_player_name  532361   99.997182
19         lateral_interception_player_id  532361   99.997182
20   lateral_kickoff_returner_player_name  532351   99.995304
21     lateral_kickoff_returner_player_id  532351   99.995304
22                  lateral_rushing_yards  532349   99.994928
23               lateral_rusher_player_id  532349   99.994928
24             lateral_rusher_player_name  532349   99.994928
25            forced_fumble_player_2_team  532338   99.992862
26       forced_fumble_player_2_player_id  532338   99.992862
27     forced_fumble_player_2_player_name  532338   99.992862
28            fumble_recovery_2_player_id  532310   99.987603
29                 fumble_recovery_2_team  532310   99.987603
30          fumble_recovery_2_player_name  532310   99.987603
31                fumble_recovery_2_yards  532310   99.987603
32                    fumbled_2_player_id  532307   99.987039
33                         fumbled_2_team  532307   99.987039
34                  fumbled_2_player_name  532307   99.987039
35       own_kickoff_recovery_player_name  532302   99.986100
36         own_kickoff_recovery_player_id  532302   99.986100
37                     safety_player_name  532266   99.979338
38                       safety_player_id  532266   99.979338
39             lateral_receiver_player_id  532238   99.974078
40           lateral_receiver_player_name  532238   99.974078
41                lateral_receiving_yards  532238   99.974078
42                      blocked_player_id  531914   99.913219
43                    blocked_player_name  531914   99.913219
44             pass_defense_2_player_name  531472   99.830195
45               pass_defense_2_player_id  531472   99.830195
46                  two_point_conv_result  530972   99.736277
47                     qb_hit_2_player_id  530952   99.732520
48                   qb_hit_2_player_name  530952   99.732520
49                  half_sack_1_player_id  530865   99.716178
50                half_sack_2_player_name  530865   99.716178
51                  half_sack_2_player_id  530865   99.716178
52                half_sack_1_player_name  530865   99.716178
53                solo_tackle_2_player_id  530604   99.667153
54                     solo_tackle_2_team  530601   99.666589
55              solo_tackle_2_player_name  530601   99.666589
56             replay_or_challenge_result  528287   99.231934
57               interception_player_name  527614   99.105519
58                 interception_player_id  527614   99.105519
59       forced_fumble_player_1_player_id  527529   99.089553
60            forced_fumble_player_1_team  527528   99.089365
61     forced_fumble_player_1_player_name  527528   99.089365
62          fumble_recovery_1_player_name  525828   98.770042
63                 fumble_recovery_1_team  525828   98.770042
64            fumble_recovery_1_player_id  525828   98.770042
65                fumble_recovery_1_yards  525828   98.770042
66                  fumbled_1_player_name  525174   98.647197
67                         fumbled_1_team  525174   98.647197
68                    fumbled_1_player_id  525174   98.647197
69                      field_goal_result  520612   97.790284
70             kickoff_returner_player_id  519899   97.656356
71           kickoff_returner_player_name  519899   97.656356
72                         sack_player_id  519593   97.598877
73                       sack_player_name  519591   97.598502
74                     extra_point_result  518303   97.356568
75                           td_player_id  516811   97.076314
76                         td_player_name  516811   97.076314
77                                td_team  516811   97.076314
78              punt_returner_player_name  514872   96.712098
79                punt_returner_player_id  514872   96.712098
80                           timeout_team  509210   95.648564
81         tackle_with_assist_1_player_id  507409   95.310269
82       tackle_with_assist_1_player_name  507409   95.310269
83              tackle_with_assist_1_team  507408   95.310082
84                       punter_player_id  507306   95.290922
85                     punter_player_name  507306   95.290922
86             pass_defense_1_player_name  506909   95.216351
87               pass_defense_1_player_id  506909   95.216351
88            tackle_for_loss_1_player_id  504420   94.748824
89          tackle_for_loss_1_player_name  504419   94.748636
90                   qb_hit_1_player_name  499665   93.855658
91                     qb_hit_1_player_id  499665   93.855658
92                      penalty_player_id  496992   93.353570
93                    penalty_player_name  496991   93.353382
94                           penalty_type  494627   92.909335
95                          penalty_yards  494610   92.906142
96                           penalty_team  494610   92.906142
97                   assist_tackle_2_team  479338   90.037492
98            assist_tackle_2_player_name  479338   90.037492
99              assist_tackle_2_player_id  479338   90.037492
100                    kicker_player_name  475578   89.331225
101                      kicker_player_id  475578   89.331225
102                           return_team  472337   88.722444
103           assist_tackle_1_player_name  454372   85.347950
104             assist_tackle_1_player_id  454372   85.347950
105                  assist_tackle_1_team  454371   85.347762
106                         kick_distance  450508   84.622147
107                               run_gap  418959   78.696072
108                     yards_after_catch  399609   75.061423
109                       receiving_yards  399599   75.059544
110                         passing_yards  399599   75.059544
111                          run_location  377142   70.841285
112                             rusher_id  377094   70.832269
113                                rusher  377094   70.832269
114                        end_clock_time  371419   69.766293
115                  rusher_jersey_number  371247   69.733985
116                         rushing_yards  371230   69.730792
117                      rusher_player_id  370848   69.659038
118                    rusher_player_name  370848   69.659038
119                              xyac_epa  345452   64.888725
120                     xyac_mean_yardage  345451   64.888537
121                          xyac_success  345451   64.888537
122                   xyac_median_yardage  345451   64.888537
123                               xyac_fd  345451   64.888537
124                                    cp  331939   62.350482
125                                  cpoe  331939   62.350482
126                  receiver_player_name  330945   62.163771
127                    receiver_player_id  330945   62.163771
128                           pass_length  325786   61.194720
129                         pass_location  325786   61.194720
130                               yac_epa  325744   61.186830
131                               air_epa  325743   61.186643
132                               yac_wpa  325743   61.186643
133                               air_wpa  325743   61.186643
134                             air_yards  324990   61.045201
135                           receiver_id  319697   60.050979
136                              receiver  319697   60.050979
137                receiver_jersey_number  318500   59.826138
138                    passer_player_name  309519   58.139172
139                      passer_player_id  309519   58.139172
140               solo_tackle_1_player_id  300057   56.361857
141             solo_tackle_1_player_name  300044   56.359415
142                    solo_tackle_1_team  300042   56.359039
143                             passer_id  287042   53.917156
144                                passer  287042   53.917156
145                  passer_jersey_number  287016   53.912273
146                                  temp  181893   34.166266
147                                  wind  181893   34.166266
148                     fantasy_player_id  169417   31.822809
149                   fantasy_player_name  169417   31.822809
150                               fantasy  153757   28.881279
151                            fantasy_id  153757   28.881279
152                               pass_oe  137926   25.907629
153                         jersey_number  136702   25.677717
154                                  name  131760   24.749425
155                                    id  131760   24.749425
156                                 xpass  126998   23.854945
157                                  down   84545   15.880693
158                         side_of_field   37688    7.079207
159                          yardline_100   37335    7.012901
160                          away_wp_post   36787    6.909966
161                          home_wp_post   36787    6.909966
162                    score_differential   28390    5.332697
163                         defteam_score   28390    5.332697
164                         posteam_score   28390    5.332697
165                               defteam   28360    5.327062
166            defteam_timeouts_remaining   28360    5.327062
167                    defteam_score_post   28360    5.327062
168               score_differential_post   28360    5.327062
169                    posteam_score_post   28360    5.327062
170            posteam_timeouts_remaining   28360    5.327062
171                               posteam   28360    5.327062
172                          posteam_type   28358    5.326686
173                           time_of_day   18531    3.480811
174                          comp_yac_epa   16186    3.040332
175                          comp_yac_wpa   16185    3.040145
176                          comp_air_epa   16185    3.040145
177                          comp_air_wpa   16185    3.040145
178                            first_down   16179    3.039018
179                          yards_gained   16179    3.039018
180                          punt_attempt   16179    3.039018
181              defensive_two_point_conv   16179    3.039018
182                          return_yards   16179    3.039018
183           defensive_two_point_attempt   16179    3.039018
184                 fourth_down_converted   16179    3.039018
185                       first_down_pass   16179    3.039018
186                          punt_blocked   16179    3.039018
187                  third_down_converted   16179    3.039018
188                    first_down_penalty   16179    3.039018
189                  fumble_out_of_bounds   16179    3.039018
190                     fumble_not_forced   16179    3.039018
191                         fumble_forced   16179    3.039018
192                        lateral_return   16179    3.039018
193                         assist_tackle   16179    3.039018
194                         complete_pass   16179    3.039018
195                     lateral_reception   16179    3.039018
196                          lateral_rush   16179    3.039018
197                    field_goal_attempt   16179    3.039018
198                     two_point_attempt   16179    3.039018
199                                fumble   16179    3.039018
200                 kickoff_inside_twenty   16179    3.039018
201                          pass_attempt   16179    3.039018
202                                  sack   16179    3.039018
203                           solo_tackle   16179    3.039018
204                      lateral_recovery   16179    3.039018
205                               penalty   16179    3.039018
206                      tackled_for_loss   16179    3.039018
207                           fumble_lost   16179    3.039018
208                  own_kickoff_recovery   16179    3.039018
209               own_kickoff_recovery_td   16179    3.039018
210                                qb_hit   16179    3.039018
211                          rush_attempt   16179    3.039018
212                                safety   16179    3.039018
213         defensive_extra_point_attempt   16179    3.039018
214                               timeout   16179    3.039018
215                        pass_touchdown   16179    3.039018
216                             touchdown   16179    3.039018
217                        rush_touchdown   16179    3.039018
218                      return_touchdown   16179    3.039018
219                   extra_point_attempt   16179    3.039018
220                    fourth_down_failed   16179    3.039018
221                       incomplete_pass   16179    3.039018
222                          interception   16179    3.039018
223                    punt_inside_twenty   16179    3.039018
224                    kickoff_fair_catch   16179    3.039018
225                 kickoff_out_of_bounds   16179    3.039018
226                    tackle_with_assist   16179    3.039018
227                       first_down_rush   16179    3.039018
228                     third_down_failed   16179    3.039018
229                    kickoff_in_endzone   16179    3.039018
230                        kickoff_downed   16179    3.039018
231                       punt_fair_catch   16179    3.039018
232                       punt_in_endzone   16179    3.039018
233                    punt_out_of_bounds   16179    3.039018
234                           punt_downed   16179    3.039018
235            defensive_extra_point_conv   16179    3.039018
236                       kickoff_attempt   16169    3.037139
237                             play_type   15642    2.938149
238                           qb_dropback   15642    2.938149
239                               weather   11201    2.103964
240                 drive_real_start_time   10420    1.957263
241                             vegas_wpa    7888    1.481660
242                                   wpa    7888    1.481660
243                               surface    7774    1.460246
244                 drive_start_yard_line    6746    1.267150
245                   drive_end_yard_line    6746    1.267150
246                               success    6096    1.145055
247                                   epa    6096    1.145055
248                                qb_epa    6096    1.145055
249                                    ep    6094    1.144680
250                   drive_play_id_ended    6066    1.139420
251                  drive_end_transition    6066    1.139420
252                                ydsnet    6061    1.138481
253                drive_ended_with_score    6061    1.138481
254                   drive_quarter_start    6061    1.138481
255                     drive_first_downs    6061    1.138481
256                drive_game_clock_start    6061    1.138481
257              drive_time_of_possession    6061    1.138481
258                                 drive    6061    1.138481
259                     drive_quarter_end    6061    1.138481
260                      drive_play_count    6061    1.138481
261                 drive_play_id_started    6061    1.138481
262                        drive_inside20    6061    1.138481
263                 drive_yards_penalized    6061    1.138481
264                drive_start_transition    6061    1.138481
265                  drive_game_clock_end    6061    1.138481
266                                 yrdln    3802    0.714157
267                                def_wp    3066    0.575909
268                              vegas_wp    3066    0.575909
269                                    wp    3066    0.575909
270                        vegas_home_wpa    3028    0.568771
271                half_seconds_remaining     268    0.050340
272                                  time     268    0.050340
273             quarter_seconds_remaining     268    0.050340
274                game_seconds_remaining     268    0.050340
275                         series_result      17    0.003193
276                    fixed_drive_result      17    0.003193